version: "3.0"

services:
  opentsdb:
    image: petergrace/opentsdb-docker
    container_name: opentsdb
    volumes:
      - opentsdb_data:/data/hbase
    ports:
      - 4242:4242
    networks:
      - opentsdb_net

volumes:
  opentsdb_data:

networks:
  opentsdb_net: