version: "3.0"

services:
  web:
    image: elkozmon/zoonavigator-web:latest
    container_name: zoonavigator-web
    ports:
     - 8001:8000
    environment:
      API_HOST: api
      API_PORT: 9000
    depends_on:
     - api
    restart: always
    networks: 
      - zknet
  api:
    image: elkozmon/zoonavigator-api:latest
    container_name: zoonavigator-api
    environment:
      SERVER_HTTP_PORT: 9000
    depends_on:
     - zoo1
    restart: always
    networks: 
      - zknet    
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    volumes:
      - zoo1_data:/data
      - zoo1_log:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks: 
      - zknet
  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    volumes:
      - zoo2_data:/data
      - zoo2_log:/datalog      
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    networks: 
      - zknet
  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    volumes:
      - zoo3_data:/data
      - zoo3_log:/datalog      
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    networks: 
      - zknet
      
networks:
  zknet:

volumes:
  zoo1_data:
  zoo1_log:
  zoo2_data:
  zoo2_log:
  zoo3_data:
  zoo3_log: